### PR TITLE
Hungarian language translation

### PR DESCRIPTION
**Pull request by szilardpal**
Hungarian language translation (hu.json)

### CODE REVIEW

**Comment by didsun** [comment]
Is there any development of the Hungarian translation?

**Comment by ironwallaby** [comment]
Oh! I'm sorry, I didn't see that this was intended to amend #52. I'll check into it in a little while and get back to you.

**Comment by ironwallaby** [comment]
There are a few issues with this pull request:

*   `hu.json` is in the project root. It needs to be in `/test_cases`.
*   The tests do not pass: there are fifteen errors in them. Please make sure your translation matches the tests, or else we have no way of verifying whether the translation is self-consistent or not!
*   This pull request and the #52 should be merged together.

There are also issues with #52. I'm going to close both PRs and ask that you correct them and resubmit. Thanks!

**Comment by szilardpal** [comment]
Hello!

Corrected and resubmitted!
Hope it will be OK now!

Best regards,
Szilard Pal

**Pull request closed without merging**
