### PR TITLE
Update ru.js

### PR DESCRIPTION
**Pull request by oleg-sh**
Fixed translation for 'clear'

### CODE REVIEW

**Comment by ironwallaby** [comment]
This change causes the tests to fail! Please also update `/test_cases/ru.json` as appropriate. Thanks!

**Comment by oleg-sh** [comment]
Done. Pull request created.
Let me know if it works, please.

**Comment by ironwallaby** [comment]
Integrated! I'll make these live on the Forecast API in the near future. Thanks!

**Comment by oleg-sh** [comment]
Thank you!

**Pull request merged**
