### PR TITLE
added persian/farsi translation

### PR DESCRIPTION
**Pull request by mohammadyaghobi**
added persian/farsi translation to languages

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thanks for your translation! We cannot accept any new translations without also accepting tests that verify that they work. Please also create a `/test_cases/fa.json` to accompany your translation and amend this pull request.

**Comment by mohammadyaghobi** [comment]
It's done.

**Comment by ironwallaby** [comment]
Hi there,

The latest version doesn't pass because now *only* the tests exist! Be sure that the tests pass in your local copy before updating your PR.

**Comment by mohammadyaghobi** [comment]
Hi,
Need to _lib/lang/fa.js_ ?
Did you mean that?

**Comment by ironwallaby** [comment]
Yes, both `lib/lang/fa.js` and `test_cases/fa.json` are required. Furthermore, when they're both present, running `npm test` should *not* return any errors.

**Comment by mohammadyaghobi** [comment]
_lib/lang/fa.js_ added again.

**Comment by ironwallaby** [comment]
Thanks. It looks like the tests don't pass, though. Please run them and fix any issues!

**Comment by ironwallaby** [comment]
Closing this due to a lack of activity. Please reopen it if you finish!

**Pull request closed without merging**
