### PR TITLE
hu.js

### PR DESCRIPTION
**Pull request by szilardpal**
Hungarian language with no errors :)

### CODE REVIEW

**Comment by ironwallaby** [comment]
Yup, seems to work this time :)

Integrated and will be deployed in our next production deploy. Thanks!

**Comment by didsun** [comment]
Which will be next update?

**Comment by ironwallaby** [comment]
It should be live already. Please let me know if it's not working for you, though!

**Comment by szilardpal** [comment]
Thanks!

I’ll give a try and respond soon if there’s any problem!

Best regards,
Szilard Pal

**Comment by szilardpal** [comment]
Hello,

I tested the translation, and there’s one problem:
the full name and also the abbreviations of the days are still english :(


i.e. Wednesday, Wed… etc.



Szilard Pal

**Comment by ironwallaby** [comment]
How are you testing the translation? These items are clearly translated in the software:

https://github.com/darkskyapp/forecast-io-translations/blob/master/lib/lang/hu.js#L83-L89

**Comment by szilardpal** [comment]
I’m using a third party script. Ok, I’ll check it again, because all the other languages seem to have the same problem… maybe there is something with the third party app.

Szilard Pal

**Comment by ironwallaby** [comment]
OK. Let me know if you find the issue persisting in the API--that's the only system we can vouch for!

**Comment by szilardpal** [comment]
Hello,

Now the hungarian language works fine, I had problems with the third party script, however I have just made a few improvements on hu.js and hu.json. Tested it and there is no error.
The are just improving the style of the language!

I’ve made the corrections on github and made changes on the files!

Thx,

Szilard Pal

**Comment by ironwallaby** [comment]
OK! You'll need to issue another pull request so we can get your updates!

**Pull request merged**
