### PR TITLE
Turkish sentences fixes

### PR DESCRIPTION
**Pull request by BQRA**

### CODE REVIEW

**Comment by ironwallaby** [comment]
Hello,

This change breaks the tests. Please also update the tests and amend this pull request!

**Comment by BQRA** [comment]
Hi, i did't changed any words, i fixed spaces. And changed location $2 to $1. Because tr.json have right sentences but tr.js is wrong ones.

**Comment by ironwallaby** [comment]
I understand that, but the tests no longer pass---so something changed enough to break them! Please run them and you will see what I mean.

**Comment by BQRA** [comment]
ok, i get it now, sorry. I send new commits.

**Comment by ironwallaby** [comment]
Merged in. These will get deployed on Monday. Thanks!

**Pull request merged**
