### PR TITLE
Added Slovenian translations sl.json

### PR DESCRIPTION
**Pull request by Metik**
Support for Slovenian Language

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thanks! You will also need to translate `/lib/lang/si.json` and make sure that the tests pass before we can accept the translation.

**Comment by Metik** [comment]
Hi,
Just added.

**Comment by ironwallaby** [comment]
Hi,

Upon reviewing this, there are some errors:

1.  Please merge your two pull requests (#78 and #79) together into one!
2.  While the tests pass, I think that there are some issues with them. In particular, `"MožNe So Rahle Padavine"` seems to exhibit a capitalization bug. (Are there other bugs like this one?)
3.  Slovenian's ISO 639-1 code is `sl`, not `si` (which is Sinhalese)!

Please correct these and I'll accept the patch.

**Comment by Metik** [comment]
Hi,
I corrected the translations.
Please check, if everything is OK.
Thanks.

**Comment by ironwallaby** [comment]
This commit is still missing `lib/lang/sl.js` from #79. Please merge it into here!

You can verify this for yourself by looking here: https://github.com/darkskyapp/forecast-io-translations/pull/78/files

**Comment by Metik** [comment]
Hi,

I added lib/lang/sl.js  into this commit.

**Comment by ironwallaby** [comment]
I have reviewed this and it looks good. We'll get it live on the API as soon as possible!

**Pull request merged**
