### PR TITLE
Serbian language

### PR DESCRIPTION
**Pull request by mrcina**
There are to many variations, tryed to cover them all. Will see in the future if this goes well.

Marko

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thanks!

I'm afraid I can't accept the patch as is: there are a few issues that will need to be fixed.

*   There's a global leak on the variable `starting_word`. Please make sure it is scoped locally.
*   There's a global leak on the variable `c`. Please make sure it is scoped locally.
*   Allowing the global variable `mscope` scares me, since globals are dangerous and it greatly obfuscates what is occurring. Is it possible to replace it with judicious use of `this`? If not, can you explain the issue that it is trying to fix? Perhaps I can help you work around needing it!

**Comment by mrcina** [comment]
global variable "mscope" removed, now passing through function "this".
added as local variable "c" and "starting_word"

That "mscope" used before as global var to inspect inside functions for some conditions. Now removed.

**Comment by ironwallaby** [comment]
Phew! I took some time to clean up your code—looks like Slovak is an exceedingly complicated language!

Thanks for the contribution, this should go live in the API later this week.

**Comment by mrcina** [comment]
By "clean up" you mean...?
Serbian it is complicated, not Slovak :)

thanks

**Comment by ironwallaby** [comment]
Yikes, sorry about that. I meant Serbian :)

By "clean up", I am referring to this diff: https://github.com/darkskyapp/forecast-io-translations/commit/f59229eda7d2472bf40cbbb70b6064188e996cbf

There was a lot of dead code, broken branches, unnecessary checks, and idempotent functions. By trimming those down, the code will be easier to maintain and run faster on our servers!

**Comment by ironwallaby** [comment]
This is now live in the API.

Be advised that the correct language code for Serbian is "sr", which is what the API (and the latest version of this module) uses.

**Comment by mrcina** [comment]
Excellent! Thanks for the info.

**Pull request merged**
