### PR TITLE
Add new indonesian translation

### PR DESCRIPTION
**Pull request by kovloq**
Add new Indonesian translation

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thanks! A few things:

*   We can't accept any commits without tests. Please add (and translate!) a `/test_cases/id.json` and make sure that the tests pass.
*   We don't want or need any `.DS_Store` files—please remove them!

**Comment by kovloq** [comment]
Hi ironwallaby,

Thank you for your information. 
I've added a test cases to the new commit. Kindly check it and let me know your thought.

Regards

**Comment by ironwallaby** [comment]
Looks great! Thanks for the translation! 👍 

I have a couple other things to integrate before deploying this live, but it should be in the API by Monday at the latest.

**Comment by ironwallaby** [comment]
This is now live.

**Comment by kovloq** [comment]
Thank You

**Pull request merged**
