### PR TITLE
Additional fixes for Slovak translation

### PR DESCRIPTION
**Pull request by martinsefcik**
Additional fixes for Slovak translation

### CODE REVIEW

**Comment by ironwallaby** [comment]
Accepted. These will get deployed with the next production update.

Thanks!

**Comment by martinsefcik** [comment]
@ironwallaby Thanks! Any ETA?

**Comment by ironwallaby** [comment]
Within 48 hours.

**Comment by martinsefcik** [comment]
Super, thanks!

**Pull request merged**
