### PR TITLE
Polished the swedish translation for more accurate translation

### PR DESCRIPTION
**Pull request by broderbluff**
Polished the swedish translation for more accurate translation

### CODE REVIEW

**Comment by ironwallaby** [comment]
Awesome! Could you please also update `/test_cases/sv.json` so that the tests pass? We can't accept any patches unless the code and the test cases match.

Thanks!

**Comment by broderbluff** [comment]
updated the test-case aswell =)

**Comment by ironwallaby** [comment]
Thanks for the update! Looks like one of the tests is still failing:

    AssertionError: 'Blandad nederbörd över helgen, med temperaturer som stiger till 32°C under torsdagen.' === 'Blandat nederbörd över helgen, med temperaturer som stiger till 32°C under torsdagen.'

Once that one's patched, too, we'll integrate your fixes. Thanks again!

**Comment by broderbluff** [comment]
It should be fixed now

**Comment by broderbluff** [comment]
It should be fixed now =)

**Comment by ironwallaby** [comment]
All merged in. Thanks! We'll likely be deploying later today, so the fixes will go live then.

**Comment by broderbluff** [comment]
Cheers!

**Pull request merged**
