### PR TITLE
Add Chinese Translations

### PR DESCRIPTION
**Pull request by sofish**
Currently working on a weather app that is based on forecast.io's api, and this is the `Chinese` version of the translations.

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thanks!

"ch" is the *country* code for China; the language code is "zh", so I switched that. Otherwise, it looks good: I merged it into master. Since it's late on a Friday, I'm not going to deploy this live; but it should go live in the near future.

**Comment by sofish** [comment]
Hi @ironwallaby , Will this be publish in this week?

**Comment by ironwallaby** [comment]
Yes. Hopefully today, but definitely by tomorrow.

**Comment by sofish** [comment]
:+1: :+1:

**Comment by ironwallaby** [comment]
I was able to get to this today: it is now live. (Just add "lang=zh" to your API query parameters and you'll get Chinese results.)

**Comment by sofish** [comment]
awesome :100:

**Pull request merged**
