### PR TITLE
Added Brazilian Portuguese translation (pt-br.json)

### PR DESCRIPTION
**Pull request by toborinojg**
{
  "Limpo":
    ["title", "clear"],

  "Possível garoa":
    ["title", "possible-very-light-precipitation"],

  "Garoa":
    ["title", "very-light-precipitation"],

  "Possível chuva fraca":
    ["title", "possible-light-precipitation"],

  "Chuva fraca":
    ["title", "light-precipitation"],

  "Chuva":
    ["title", "medium-precipitation"],

  "Chuva Forte":
    ["title", "heavy-precipitation"],

  "Possíveis Chuviscos":
    ["title", "possible-very-light-rain"],

  "Chuviscos":
    ["title", "very-light-rain"],

  "Possível Chuva Fraca":
    ["title", "possible-light-rain"],

  "Chuva Fraca":
    ["title", "light-rain"],

  "Chuva":
    ["title", "medium-rain"],

  "Chuva Forte":
    ["title", "heavy-rain"],

  "Possível Granizo Muito Fraco":
    ["title", "possible-very-light-sleet"],

  "Granizo Muito Fraco":
    ["title", "very-light-sleet"],

  "Possível Granizo Fraco":
    ["title", "possible-light-sleet"],

  "Granizo Fraco":
    ["title", "light-sleet"],

  "Granizo":
    ["title", "medium-sleet"],

  "Granizo Forte":
    ["title", "heavy-sleet"],

  "Possível Neve Muito Fraca" :
    ["title", "possible-very-light-snow"],

  "Neve Muito Fraca" :
    ["title", "very-light-snow"],

  "Possível Neve Fraca":
    ["title", "possible-light-snow"],

  "Neve Fraca":
    ["title", "light-snow"],

  "Neve":
    ["title","medium-snow"],

  "Muita neve":
    ["title", "heavy-snow"],

  "Vento Fraco":
    ["title", "light-wind"],

  "Vento":
    ["title", "medium-wind"],

  "Vento Forte":
    ["title", "heavy-wind"],

  "Seco":
    ["title", "low-humidity"],

  "Úmido":
    ["title", "high-humidity"],

  "Nevoeiro":
    ["title", "fog"],

  "Ligeiramente Nublado":
    ["title", "light-clouds"],

  "Nublado":
    ["title", "medium-clouds"],

  "Muito Nublado":
    ["title", "heavy-clouds"],

  "Seco e Vento Fraco":
    ["title", ["and", "low-humidity", "light-wind"]],

  "Chuviscos e Vento Forte":
    ["title",["and","very-light-rain","heavy-wind"]],

  "Úmido e Ligeiramente Nublado":
    ["title",["and","high-humidity","light-clouds"]],

  "Limpo na próxima hora.":
    ["sentence",["for-hour","clear"]],

  "Neve muito fraca dentro de 30 min.":
    ["sentence",["starting-in","very-light-snow",["minutes", 30]]],

  "Chuva fraca termina daqui a 15 min.":
    ["sentence",["stopping-in","light-rain", ["minutes", 15]]],

  "Granizo forte dentro de 20 min, termina 30 min mais tarde.":
    ["sentence",
      ["starting-then-stopping-later",
        "heavy-sleet",
        ["minutes", 20],
        ["minutes", 30]]],

  "Chuva termina dentro de 25 min, recomeça 8 min mais tarde.":
    ["sentence",
      ["stopping-then-starting-later",
        "medium-rain",
        ["minutes", 25],
        ["minutes", 8]]],

  "Nublado durante todo o dia.":
    ["sentence",["for-day","medium-clouds"]],

  "Granizo muito fraco começa durante a manhã.":
    ["sentence",["starting", "very-light-sleet", "morning"]],

  "Vento até hoje de madrugada.":
    ["sentence", ["until","medium-wind", "today-night"]],

  "Chuvas fortes até tarde.":
    ["sentence",["until","heavy-precipitation","afternoon"]],

  "Vento fraco durante tarde.":
    ["sentence",["during","light-wind","afternoon"]],

  "Neve durante noite de hoje e amanhã de manhã.":
    ["sentence",["during",
      "medium-snow",
      ["and","later-today-evening","tomorrow-morning"]]],

  "Chuva forte até manhã de hoje, recomeça hoje à noite.":
    ["sentence",["until-starting-again",
      "heavy-rain",
      "later-today-morning",
      "today-evening"]],
  
  "Muito nublado esta noite até à madrugada.":
    ["sentence",["starting-continuing-until",
      "heavy-clouds",
      "evening",
      "night"]],

  "Granizo fraco durante tarde de hoje e nevoeiro durante amanhã de manhã.":
    ["sentence",["and",
      ["during","light-sleet", "later-today-afternoon"],
      ["during","fog","tomorrow-morning"]]],

  "Vento forte começa esta manhã, continua até à tarde, e granizo durante amanhã de manhã.":
    ["sentence", ["and",
      ["starting-continuing-until",
        "heavy-wind",
        "morning",
        "afternoon"],
      ["during", "medium-sleet", "tomorrow-morning"]]],

  "Muito nublado começa durante a de madrugada e nevão durante amanhã à tarde.":
    ["sentence",["and",
    ["starting", "heavy-clouds", "later-today-night"],
    ["during", "heavy-snow", "tomorrow-afternoon"]]],

  "Seco durante hoje de madrugada e aguaceiros fracos começa esta amanhã à noite, continua até à amanhã de madrugada.":
    ["sentence", ["and",
      ["during", "low-humidity", "today-night"],
      ["starting-continuing-until",
        "light-precipitation",
        "tomorrow-evening",
        "tomorrow-night"]]],

  "Neve (5 cm.) durante madrugada.":
    ["sentence", ["during",
      ["parenthetical", "medium-snow", ["centimeters", 5]],
      "night"]],

  "Neve fraca (2 cm.) durante manhã de hoje.":
    ["sentence", ["during",
      ["parenthetical", "light-snow", ["centimeters", 2]],
      "later-today-morning"]],

  "Neve (menos de 1 cm.) durante tarde.":
    ["sentence", ["during",
      ["parenthetical", "medium-snow", ["less-than", ["centimeters", 1]]],
      "afternoon"]],

  "Sem chuvas durante toda a semana, com as temperaturas chegando a um máximo de 35\u00B0C amanhã.":
    ["sentence", ["with",
      ["for-week", "no-precipitation"],
      ["temperatures-peaking",
        ["celsius", 35],
        "tomorrow"]]],

  "Chuvas esparsas durante todo o fim de semana, com as temperaturas subindo aos 32\u00B0C quinta-feira.":
    ["sentence", ["with",
      ["over-weekend", "mixed-precipitation"],
      ["temperatures-rising",
        ["celsius", 32],
        "thursday"]]],

  "Chuviscos durante segunda-feira, com as temperaturas descendo até 15\u00B0C sexta-feira.":
    ["sentence", ["with",
      ["during", "very-light-rain", "monday"],
      ["temperatures-valleying",
        ["celsius", 15],
        "friday"]]],
  
  "Neve fraca durante terça-feira e quarta-feira, com as temperaturas descendo até 0\u00B0C domingo.":
    ["sentence", ["with",
      ["during", "light-snow", ["and", "tuesday", "wednesday"]],
      ["temperatures-falling",
        ["celsius", 0],
        "sunday"]]],

  "Chuvas de hoje até sábado, com as temperaturas subindo até 37\u00B0C segunda-feira.":
    ["sentence", ["with",
      ["during",
        "medium-precipitation",
        ["through", "today", "saturday"]],
      ["temperatures-peaking",
        ["celsius", 37],
        "monday"]]]

}

### CODE REVIEW

**Comment by ironwallaby** [comment]
I'm afraid I'm not very knowledgeable about Portuguese: is Brazilian Portuguese close enough to European Portuguese that we can simply reconcile the two? (That is, avoid terms that are particular to one or the other?) If it is at all possible, we'd prefer to go this route, since we don't like having to maintain multiple variants of each language. (For example, we've spent a lot of time tweaking the English translations to avoid terminology particular to the USA or the UK, since we don't want to support `en-US` an `en-GB` separately!)

**Comment by toborinojg** [comment]
Hi,

We use a different syntax and phrase structure.
The two forms are very distinct. Most of the weather sentences are in a
present continous (It will start *raining* in...).
In Brazil we use the form
- Chovendo em xxx minutos.
In Portugal they will use
- Estará a chover em xxx minutos.

Even same words has different orthography.
Moist -> Úmido in Brazil
In Portugal it will be Húmido.

Most of the website APIs and social networks has their own Brazilian
Portuguese version.
Otherwise it doesn

[]s

Jose Geraldo Magalhaes
jose.geraldo@toborino.com

*Toborino Software*
toborino.com
(0xx11) 3868 3625

**Comment by toborinojg** [comment]
​sorry, I hit enter to send the message.

Continuing...

If you want users in both sides of portuguese speakers (+/- 400 million
people) you must have a portuguese and brazilian portuguese versions.

[]s

Jose Geraldo Magalhaes
jose.geraldo@toborino.com

*Toborino Software*
toborino.com
(0xx11) 3868 3625

**Comment by ironwallaby** [comment]
Understood, thanks for the input. It seems reasonable therefore to have `pt` and `pt-br`.

Before I can accept the patch, we'll also need a `/test_cases/pt-br.json` file: this will create tests to verify that the translations provided don't have any obvious bugs in them. Once we have the tests and they all pass, I'll be able to accept this patch!

**Comment by toborinojg** [comment]
You are welcome!
I sent a pull request on GitHub
https://github.com/darkskyapp/forecast-io-translations/pull/76
This is the pt-br.json.

[]s

Jose Geraldo Magalhaes
jose.geraldo@toborino.com

*Toborino Software*
toborino.com
(0xx11) 3868 3625

**Comment by ironwallaby** [comment]
Ah, I follow what's up. We have `pt-br.json`, but we also need `/lib/lang/pt-br.js`. That is, you have the tests, but not the code that does the translations! Please read the README for more details!

**Comment by ironwallaby** [comment]
Closing this due to a lack of activity. Please reopen it if you finish!

**Pull request closed without merging**
