### PR TITLE
Added Croatian translation

### PR DESCRIPTION
**Pull request by kristijandraca**

### CODE REVIEW

**Comment by ironwallaby** [comment]
Hi there! The tests given don't seem to pass... please double check them!

**Comment by kristijandraca** [comment]
@ironwallaby can you tell me on what line of code because I can't setup environment for testing

**Comment by ironwallaby** [comment]
1) translation language hr should translate ["title","medium-precipitation"] to "padaline":
         AssertionError: 'Padaline' === 'padaline'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      2) translation language hr should translate ["title","possible-light-snow"] to "Moguće je sitan snijeg":
         AssertionError: 'Moguć je sitan snijeg' === 'Moguće je sitan snijeg'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      3) translation language hr should translate ["sentence",["for-day","medium-clouds"]] to "Pretežno oblačno tokom cijelog dana.":
         AssertionError: 'Pretežno oblačno tijekom cijelog dana.' === 'Pretežno oblačno tokom cijelog dana.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      4) translation language hr should translate ["sentence",["until","medium-wind","today-night"]] to "Vjetrovito do u noć.":
         AssertionError: 'Vjetrovito do u noći.' === 'Vjetrovito do u noć.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      5) translation language hr should translate ["sentence",["starting-continuing-until","heavy-clouds","evening","night"]] to "Oblačno počinje večeras, ostaje do u noć.":
         AssertionError: 'Oblačno počinje večer, ostaje do po noći.' === 'Oblačno počinje večeras, ostaje do u noć.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      6) translation language hr should translate ["sentence",["and",["starting-continuing-until","heavy-wind","today-morning","today-afternoon"],["during","medium-sleet","tomorrow-morning"]]] to "Opasno vjetrovito počinje ovo jutro, ostaje do poslijepodne, i susnježica sutra ujutro.":
         AssertionError: 'Jako vjetrovito počinje ovo jutro, ostaje do poslijepodne, i susnježica sutra ujutro.' === 'Opasno vjetrovito počinje ovo jutro, ostaje do poslijepodne, i susnježica sutra ujutro.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      7) translation language hr should translate ["sentence",["and",["during","low-humidity","today-night"],["starting-continuing-until","light-precipitation","tomorrow-evening","tomorrow-night"]]] to "Suho u noć i slabe padaline počinje sutra navečer, ostaje do sutra u noć.":
         AssertionError: 'Suho u noći i slabe padaline počinje sutra navečer, ostaje do sutra u noć.' === 'Suho u noć i slabe padaline počinje sutra navečer, ostaje do sutra u noć.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      8) translation language hr should translate ["sentence",["during",["parenthetical","medium-snow",["inches",5]],"night"]] to "Snijeg (5 inča) u noć.":
         AssertionError: 'Snijeg (5 inča) po noći.' === 'Snijeg (5 inča) u noć.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      9) translation language hr should translate ["sentence",["for-day",["parenthetical","heavy-snow",["inches",["range",8,12]]]]] to "Jak snijeg (8–12 inča) tokom cijelog dana.":
         AssertionError: 'Jak snijeg (8–12 inča) tijekom cijelog dana.' === 'Jak snijeg (8–12 inča) tokom cijelog dana.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      10) translation language hr should translate ["sentence",["with",["for-week","no-precipitation"],["temperatures-peaking",["fahrenheit",85],"tomorrow"]]] to "Nema padavina tokom tjedna, sa temperaturom najviše do 85°F sutra.":
         AssertionError: 'Nema padalina tijekom tjedna, sa temperaturom najviše do 85°F sutra.' === 'Nema padavina tokom tjedna, sa temperaturom najviše do 85°F sutra.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      11) translation language hr should translate ["sentence",["with",["over-weekend","mixed-precipitation"],["temperatures-rising",["celsius",32],"thursday"]]] to "Različite padaline tokom vikenda, sa temperaturom raste do 32°C u četvrtak.":
         AssertionError: 'Različite padaline tijekom vikenda, sa temperaturom raste do 32°C u četvrtak.' === 'Različite padaline tokom vikenda, sa temperaturom raste do 32°C u četvrtak.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      12) translation language hr should translate ["sentence",["with",["during","light-snow",["and","tuesday","wednesday"]],["temperatures-falling",["celsius",0],"sunday"]]] to "Sitan snijeg u utorak i srijeda, sa temperaturom pada do 0°C u nedjelju.":
         AssertionError: 'Sitan snijeg u utorak i srijedu, sa temperaturom pada do 0°C u nedjelju.' === 'Sitan snijeg u utorak i srijeda, sa temperaturom pada do 0°C u nedjelju.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      13) translation language hr should translate ["sentence",["with",["during","medium-precipitation",["through","today","saturday"]],["temperatures-peaking",["fahrenheit",100],"monday"]]] to "padaline danas do u subotu, sa temperaturom najviše do 100°F u ponedjeljak.":
         AssertionError: 'Padaline danas do u subotu, sa temperaturom najviše do 100°F u ponedjeljak.' === 'padaline danas do u subotu, sa temperaturom najviše do 100°F u ponedjeljak.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by kristijandraca** [comment]
Try to run test now. Thanks for help

**Comment by ironwallaby** [comment]
Sorry for the delay. This is much improved, but the following tests are still failing:

      1) translation language hr should translate ["sentence",["starting-continuing-until","heavy-clouds","evening","night"]] to "Oblačno počinje večeras, ostaje do noći.":
         AssertionError: 'Oblačno počinje večer, ostaje do noći.' === 'Oblačno počinje večeras, ostaje do noći.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)
    
      2) translation language hr should translate ["sentence",["with",["for-week","no-precipitation"],["temperatures-peaking",["fahrenheit",85],"tomorrow"]]] to "Nema padalina tokom tjedna, sa temperaturom najviše do 85°F sutra.":
         AssertionError: 'Nema padalina tijekom tjedna, sa temperaturom najviše do 85°F sutra.' === 'Nema padalina tokom tjedna, sa temperaturom najviše do 85°F sutra.'
          at Context.<anonymous> (/home/jason/src/forecast-io-translations/test.js:134:22)
          at callFn (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:250:21)
          at Test.Runnable.run (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runnable.js:243:7)
          at Runner.runTest (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:373:10)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:451:12
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:298:14)
          at /home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:308:7
          at next (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:246:23)
          at Immediate._onImmediate (/home/jason/src/forecast-io-translations/node_modules/mocha/lib/runner.js:275:5)
          at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by kristijandraca** [comment]
I added new commit. I hope this time will pass the tests.

**Comment by ironwallaby** [comment]
Yup, that did it! I've merged it in. Thanks for your work!

We'll have this deployed to the API by end-of-week at the latest.

**Comment by kristijandraca** [comment]
Awesome!

**Pull request merged**
